name: Build

on:
  push:

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Download Code Climate test reporter
        run: |
          curl -L -o cc-test-reporter https://github.com/codeclimate/test-reporter/releases/download/v0.11.4/test-reporter-linux-amd64
          chmod +x cc-test-reporter

      - name: Before build
        run: ./cc-test-reporter before-build

      - name: Run Gradle build
        run: make build

      - name: Generate coverage report
        run: make report

      - name: After build
        run: ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
